Connecting my google drive to google colab, to uploud the dataset permanently

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Importing important libraries to hande and deal with data like pandas ans numpy

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

Uploading the dataset

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/dataset (1).csv')
#printing the head (first 5 rows) instead of printing the whole dataset
df.head()

I_Id    I_W  I_Fat_C     I_Vis    I_MRP_JD             I_category  \
0  FDA15   9.30  Low Fat  0.016172  225.644532                  Dairy   
1  DRC01   5.92  Regular  0.019403   82.551132            Soft Drinks   
2  FDN15  17.50  Low Fat  0.016885  148.828780                   Meat   
3  FDX07  19.20  Regular  0.000000  177.567450  Fruits and Vegetables   
4  NCD19   8.93  Low Fat  0.000000   86.521594              Household   

   I_MRP_US    O_Id  O_Establ_Y  O_Size I_Recalled O_Loc_T            O_T  \
0  317.8092  OUT049        2009  Medium         NO  Tier 1      Carrefour   
1  116.2692  OUT018        2019  Medium        YES  Tier 3         C-Town   
2  209.6180  OUT049        2009  Medium         NO  Tier 1      Carrefour   
3  250.0950  OUT010        2008     NaN         NO  Tier 3  Family Basket   
4  121.8614  OUT013        1997    High         NO  Tier 3      Carrefour   

   I_O_Sales  
0  3915.1380  
1   623.4228  
2  2277.2700  
3   912.3800  
4  1174.7052

# **DATA PREPROCESSING**

In [ ]:
df.head()

I_W     I_Vis  I_MRP_US  O_Establ_Y  O_Size  I_O_Sales  O_Loc_T_Tier 1  \
0   9.30  0.016172  317.8092        2009       1  3915.1380               1   
1   5.92  0.019403  116.2692        2019       1   623.4228               0   
2  17.50  0.016885  209.6180        2009       1  2277.2700               1   
3  19.20  0.070607  250.0950        2008       1   912.3800               0   
4   8.93  0.070607  121.8614        1997       0  1174.7052               0   

   O_Loc_T_Tier 2  O_Loc_T_Tier 3  O_T_C-Town  O_T_Carrefour  O_T_Cozmo  \
0               0               0           0              1          0   
1               0               1           1              0          0   
2               0               0           0              1          0   
3               0               1           0              0          0   
4               0               1           0              1          0   

   O_T_Family Basket  
0                  0  
1                  0  
2                  0  
3                  1  
4                  0

In [ ]:
df2=df.copy(deep=True)
df2['I_Id'] = pd.factorize(df2['I_Id'])[0]
df2['I_Fat_C'] = pd.factorize(df2['I_Fat_C'])[0]
df2['I_category'] = pd.factorize(df2['I_category'])[0]
df2['O_Id'] = pd.factorize(df2['O_Id'])[0]
df2['O_Size'] = pd.factorize(df2['O_Size'])[0]
df2['I_Recalled'] = pd.factorize(df2['I_Recalled'])[0]
df2['O_T'] = pd.factorize(df2['O_T'])[0]
df2['O_Loc_T'] = pd.factorize(df2['O_Loc_T'])[0]
correlation_matrix = df2.corr()
correlation_matrix
print(correlation_matrix['I_O_Sales'])
print(correlation_matrix['O_T'])

In [ ]:
df=df.drop(['I_Id','I_MRP_JD','I_category','O_Id','I_Recalled'],axis=1)
df

In [ ]:
df.duplicated().sum()

In [ ]:
df

In [ ]:
df.describe()

In [ ]:
df['I_Vis'] = df['I_Vis'].replace(0, np.nan)
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
df

In [ ]:
median=df['I_W'].median()
mean=df['I_Vis'].mean()
df['I_W']=df['I_W'].fillna(median)
df['I_Vis']=df['I_Vis'].fillna(mean)
df['O_Size']=df['O_Size'].fillna(-1)
df['O_Size']=np.where(((df['O_Size']==-1)&(df['O_Loc_T']=='Tier 2')),'Small',df['O_Size'])
df['O_Size']=np.where(((df['O_Size']==-1)&(df['O_Loc_T']=='Tier 3')),'Medium',df['O_Size'])

In [ ]:
df.isnull().sum()

In [ ]:
df['I_Fat_C'].unique()
df['I_Fat_C']=df['I_Fat_C'].replace({'LF':'Low Fat','low fat':'Low Fat','reg':'Regular'})
df['I_Fat_C'].unique()

In [ ]:
label = LabelEncoder()
df['O_Size'] = label.fit_transform(df['O_Size'])

In [ ]:
dfk=df.copy(deep=True)
dfk

In [ ]:
fat = pd.get_dummies(df[['I_Fat_C']])
loc = pd.get_dummies(df[['O_Loc_T']])
t = pd.get_dummies(df[['O_T']])
df = pd.concat([df,loc,t],axis = 1)
df = df.drop(['I_Fat_C','O_Loc_T','O_T'],axis =1 )
df

In [ ]:
df.to_csv('RESULT1.csv')

In [ ]:
df #Without normalization
dfmn=df.copy(deep=True)
dfz=df.copy(deep=True)
dfmn['I_W']=(df['I_W']-df['I_W'].min())/(df['I_W'].max()-df['I_W'].min())
dfmn['I_Vis']=(df['I_Vis']-df['I_Vis'].min())/(df['I_Vis'].max()-df['I_Vis'].min())
dfmn['I_MRP_US']=(df['I_MRP_US']-df['I_MRP_US'].min())/(df['I_MRP_US'].max()-df['I_MRP_US'].min())
dfmn['O_Establ_Y']=(df['O_Establ_Y']-df['O_Establ_Y'].min())/(df['O_Establ_Y'].max()-df['O_Establ_Y'].min())
dfmn
dfz['I_W'] =(df['I_W'] -df['I_W'].mean())/df['I_W'].std()
dfz['I_Vis'] =(df['I_Vis'] -df['I_Vis'].mean())/df['I_Vis'].std()
dfz['I_MRP_US'] =(df['I_MRP_US'] -df['I_MRP_US'].mean())/df['I_MRP_US'].std()
dfz['O_Establ_Y'] =(df['O_Establ_Y'] -df['O_Establ_Y'].mean())/df['O_Establ_Y'].std()
dfz

# **LINEAR REGRESSION**

In [ ]:
x=dfmn.drop('I_O_Sales',axis=1)
y=dfmn['I_O_Sales']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30,random_state=0)

In [ ]:
X_b = np.c_[np.ones((X_train.shape[0], 1)), X_train]
X_test = np.c_[np.ones((X_test.shape[0], 1)), X_test]

In [ ]:
learning_rate = 0.1   # learning rate #0.0000002--.31 #0.00000001-- 0.24 #0.0000001--.31
n_iterations = 10000 #number of iteration
m = X_train.shape[0]    #number of rows in the dataset

beta = np.random.randn(X_train.shape[1]+1)  # random initialization for beta
print(f'inital beta {beta}')
for iteration in range(n_iterations):
    #Here we have to compute the gradient
    gradients = 2/m * X_b.T.dot(X_b.dot(beta) - y_train)

    #Here we have to update the values of beta
    beta = beta - (learning_rate * gradients)

    print(f'beta in iteration {iteration+1} is {beta}')

Streaming output truncated to the last 5000 lines.
beta in iteration 8751 is [  443.36127695   -32.08605805   -48.37885555  3618.00867326
   174.2327243   -104.17972952   181.57248711   203.79952577
    58.10647072   -63.82999304   268.84908486  1793.30530417
 -1553.05704786]
beta in iteration 8752 is [  443.36127697   -32.08605805   -48.37885555  3618.00867325
   174.23272429  -104.17972953   181.57248712   203.79952579
    58.10647071   -63.82999302   268.84908485  1793.30530418
 -1553.05704785]
beta in iteration 8753 is [  443.36127699   -32.08605806   -48.37885556  3618.00867325
   174.23272428  -104.17972954   181.57248713   203.79952581
    58.1064707    -63.829993     268.84908485  1793.30530418
 -1553.05704785]
beta in iteration 8754 is [  443.36127701   -32.08605806   -48.37885556  3618.00867325
   174.23272427  -104.17972956   181.57248714   203.79952583
    58.10647069   -63.82999298   268.84908484  1793.30530419
 -1553.05704784]
beta in iteration 8755 is [  443.36127703   -

In [ ]:
y_pred=np.dot(X_test,beta)

In [ ]:
from math import sqrt
from statistics import variance
#evaluate using r squared
x1 = (y_test - y_pred)
x2 = x1**2
rss = x2.sum()
xx1 = (y_test - y_test.mean())
xx2 = xx1**2
tss = xx2.sum()
r2 = 1 - (rss / tss)
print('R squared = ',r2)
MSE = np.square(np.subtract(y_test,y_pred)).mean()
rsme = sqrt(MSE)
MAE=np.mean(np.abs(y_test - y_pred))
print("MSE=",MSE)
print("RSME=",rsme)
print("MAE=",MAE)

R squared =  0.5622054801092562
MSE= 1333120.3241385755
RSME= 1154.6082990081854
MAE= 862.6229402976047


# **KNN**

In [ ]:
dfk

I_W  I_Fat_C     I_Vis  I_MRP_US  O_Establ_Y  O_Size O_Loc_T  \
0      9.300  Low Fat  0.016172  317.8092        2009       1  Tier 1   
1      5.920  Regular  0.019403  116.2692        2019       1  Tier 3   
2     17.500  Low Fat  0.016885  209.6180        2009       1  Tier 1   
3     19.200  Regular  0.070607  250.0950        2008       1  Tier 3   
4      8.930  Low Fat  0.070607  121.8614        1997       0  Tier 3   
...      ...      ...       ...       ...         ...     ...     ...   
8518   6.865  Low Fat  0.056908  282.5218        1997       0  Tier 3   
8519   8.380  Regular  0.047107  176.1570        2012       2  Tier 2   
8520  10.600  Low Fat  0.035311  153.1224        2014       2  Tier 2   
8521   7.210  Regular  0.145346  171.1332        2019       1  Tier 3   
8522  14.800  Low Fat  0.045003  143.4670        2007       2  Tier 1   

                O_T  I_O_Sales  
0         Carrefour  3915.1380  
1            C-Town   623.4228  
2         Carrefour  2277.2700  
3     Family Basket   912.3800  
4         Carrefour  1174.7052  
...             ...        ...  
8518      Carrefour  2958.3834  
8519      Carrefour   729.2850  
8520      Carrefour  1373.1136  
8521         C-Town  2025.5976  
8522      Carrefour   945.6700  

[8523 rows x 9 columns]

In [ ]:
dfk['O_T'] = label.fit_transform(dfk['O_T'])
fat = pd.get_dummies(dfk[['I_Fat_C']])
loc = pd.get_dummies(dfk[['O_Loc_T']])
dfk = pd.concat([dfk,loc,fat],axis = 1)
dfk= dfk.drop(['I_Fat_C','O_Loc_T'],axis =1 )
dfkmn=dfk.copy(deep=True)
dfkz=dfk.copy(deep=True)
dfkmn['I_O_Sales']=(dfk['I_O_Sales']-dfk['I_O_Sales'].min())/(dfk['I_O_Sales'].max()-dfk['I_O_Sales'].min())
dfkmn['I_W']=(dfk['I_W']-dfk['I_W'].min())/(dfk['I_W'].max()-dfk['I_W'].min())
dfkmn['I_Vis']=(dfk['I_Vis']-dfk['I_Vis'].min())/(dfk['I_Vis'].max()-dfk['I_Vis'].min())
dfkmn['I_MRP_US']=(dfk['I_MRP_US']-dfk['I_MRP_US'].min())/(dfk['I_MRP_US'].max()-dfk['I_MRP_US'].min())
dfkmn['O_Establ_Y']=(dfk['O_Establ_Y']-dfk['O_Establ_Y'].min())/(dfk['O_Establ_Y'].max()-dfk['O_Establ_Y'].min())
dfkmn
dfkz['I_W'] =(dfk['I_W'] -dfk['I_W'].mean())/dfk['I_W'].std()
dfkz['I_Vis'] =(dfk['I_Vis'] -dfk['I_Vis'].mean())/dfk['I_Vis'].std()
dfkz['I_MRP_US'] =(dfk['I_MRP_US'] -dfk['I_MRP_US'].mean())/dfk['I_MRP_US'].std()
dfkz['O_Establ_Y'] =(dfk['O_Establ_Y'] -dfk['O_Establ_Y'].mean())/dfk['O_Establ_Y'].std()
dfkz['I_O_Sales'] =(dfk['I_O_Sales'] -dfk['I_O_Sales'].mean())/dfk['I_O_Sales'].std()
dfkz
dfk

I_W     I_Vis  I_MRP_US  O_Establ_Y  O_Size  O_T  I_O_Sales  \
0      9.300  0.016172  317.8092        2009       1    1  3915.1380   
1      5.920  0.019403  116.2692        2019       1    0   623.4228   
2     17.500  0.016885  209.6180        2009       1    1  2277.2700   
3     19.200  0.070607  250.0950        2008       1    3   912.3800   
4      8.930  0.070607  121.8614        1997       0    1  1174.7052   
...      ...       ...       ...         ...     ...  ...        ...   
8518   6.865  0.056908  282.5218        1997       0    1  2958.3834   
8519   8.380  0.047107  176.1570        2012       2    1   729.2850   
8520  10.600  0.035311  153.1224        2014       2    1  1373.1136   
8521   7.210  0.145346  171.1332        2019       1    0  2025.5976   
8522  14.800  0.045003  143.4670        2007       2    1   945.6700   

      O_Loc_T_Tier 1  O_Loc_T_Tier 2  O_Loc_T_Tier 3  I_Fat_C_Low Fat  \
0                  1               0               0                1   
1                  0               0               1                0   
2                  1               0               0                1   
3                  0               0               1                0   
4                  0               0               1                1   
...              ...             ...             ...              ...   
8518               0               0               1                1   
8519               0               1               0                0   
8520               0               1               0                1   
8521               0               0               1                0   
8522               1               0               0                1   

      I_Fat_C_Regular  
0                   0  
1                   1  
2                   0  
3                   1  
4                   0  
...               ...  
8518                0  
8519                1  
8520                0  
8521                1  
8522                0  

[8523 rows x 12 columns]

In [ ]:
X=dfk.drop(['O_T'], axis=1)
y= dfk[['O_T']]

In [ ]:
from scipy.stats import mode

#Euclidean Distance
def eucledian(p1,p2):
    dist = np.sqrt(np.sum((p1-p2)**2))
    return dist

#Function to calculate KNN
def predict(x_train, y , x_input, k):
    op_labels = []

    #Loop through the Datapoints to be classified
    for item in x_input:

        point_dist = []

        #Loop through each training Data
        for j in range(len(x_train)):
            distances = eucledian(np.array(x_train[j,:]) , item)
            #Calculating the distance
            point_dist.append(distances)
        point_dist = np.array(point_dist)

        #Sorting the array while preserving the index
        #Keeping the first K datapoints
        dist = np.argsort(point_dist)[:k]

        #Labels of the K datapoints from above
        labels = y[dist]

        #Majority voting
        lab = mode(labels)
        lab = lab.mode[0]
        op_labels.append(lab)

    return op_labels

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [ ]:
y_train=y_train.to_numpy()
X_train=X_train.to_numpy()
X_test=X_test.to_numpy()

In [ ]:
y_pred = predict(X_train,y_train,X_test ,3)

In [ ]:
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='micro')
recall = recall_score(y_test, y_pred, average='micro')
f1 = f1_score(y_test, y_pred, average='micro')
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1-score:', f1)


Accuracy: 0.7653958944281525
Precision: 0.7653958944281525
Recall: 0.7653958944281525
F1-score: 0.7653958944281525


In [ ]:
pred=pd.DataFrame(y_pred)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  24  143    0    9]
 [  65 1005   30   31]
 [   2   92   79    1]
 [   1   26    0  197]]
